name: Codeledge Auto Generate

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: codeledge/generate-docs@v1
        with:
          job-token: ${{ secrets.CODELEDGE_JOB_TOKEN }}